/**
 * What a conversation flow is.
 *
 * One zod schema, and everything downstream derives from it: the canvas in
 * /admin/flow, the server actions that save a draft, the runtime in ./run.ts,
 * and — later — the patches the nightly improver proposes. A model that invents
 * a node kind is rejected by `flowDoc.parse()` before it can reach a draft,
 * which is the whole reason the boundary is a schema rather than an interface.
 *
 * Nothing here touches the database or any Node builtin: the builder runs this
 * in the browser. Same constraint that split `../matching.ts` out of
 * `../answers.ts`, and for the same reason — importing a module that opens a
 * Mongo connection pulls the driver into the client bundle, which does not
 * build.
 */

import { z } from "zod";

const trimmed = z.string().trim();

/**
 * Ids are opaque strings, generated by whatever creates the node.
 *
 * Long enough that a readable id — the migration builds `e-<from>-choice-<n>`
 * out of two slugs — is not forced to become a uuid nobody can grep for. They
 * are never shown to a visitor and never parsed, only compared.
 */
const id = trimmed.min(1).max(128);

/* ── Slots ───────────────────────────────────────────────────────────────── */

/**
 * A fact the conversation collected.
 *
 * Deliberately three kinds rather than a free-form type. `enum` is the one that
 * pays for itself — a fixed set of options renders as buttons, and a tapped
 * button is an exact transition with no matching and no model call. `text` and
 * `contact` exist because two questions genuinely need free text: which country
 * issued a document, and how to reach someone.
 */
export const slotKind = z.enum(["enum", "text", "contact"]);

export const slot = z.object({
  /** How conditions and reply templates refer to it: `{{issuing_country}}`. */
  key: trimmed.regex(/^[a-z][a-z0-9_]{0,39}$/, "lower_snake_case, starting with a letter"),
  /** What the admin sees in the inspector. */
  label: trimmed.min(1).max(80),
  kind: slotKind,
  /** `enum` only. Each option is offered as a button and can carry its own edge. */
  options: z.array(trimmed.min(1).max(60)).max(12).default([]),
});

/* ── Intents ─────────────────────────────────────────────────────────────── */

/**
 * A thing people ask, in all the ways they ask it.
 *
 * This replaces `keywords` / `trigger_groups` / `any_keywords` on the old answer
 * bank. `phrases` are embedded at publish time and matched by cosine, so a
 * phrasing nobody thought to list still lands — which was the point of the
 * change.
 *
 * `hintKeywords` are the old ALL-groups, kept rather than discarded. They do two
 * jobs: they are what the widget matches against as the visitor types (the
 * browser cannot embed anything), and they are the fallback the runtime uses
 * when no embedding key is usable. An intent with neither phrases nor hint
 * keywords can never match, which `lint.ts` reports.
 */
export const intent = z.object({
  id,
  /** Author-facing, e.g. "cost of attestation". Never shown to a visitor. */
  name: trimmed.min(1).max(120),
  phrases: z.array(trimmed.min(1).max(300)).max(60).default([]),
  /** Each inner array is an AND-group, exactly as `triggersMatch` reads it. */
  hintKeywords: z.array(z.array(trimmed.min(1).max(60)).max(12)).max(20).default([]),
});

/* ── Nodes ───────────────────────────────────────────────────────────────── */

/** Where the node sits on the canvas. Presentation only — the runtime never
 *  reads it — but it lives on the node so a layout survives a publish. */
const point = z.object({ x: z.number(), y: z.number() });

const nodeBase = { id, position: point.default({ x: 0, y: 0 }) };

/**
 * The reply nodes and the routing nodes.
 *
 * A discriminated union rather than one node with optional fields, so that
 * `switch (node.kind)` in the runtime is exhaustive and adding a kind is a type
 * error everywhere it needs to be handled.
 */
export const flowNode = z.discriminatedUnion("kind", [
  /** Where a conversation starts. Exactly one per flow; its outgoing edges are
   *  the opening suggestions. */
  z.object({ ...nodeBase, kind: z.literal("start") }),

  /** An answer. This is what every migrated answer-bank entry becomes. */
  z.object({
    ...nodeBase,
    kind: z.literal("say"),
    /** Markdown, as the answer bank stored it. `{{slot_key}}` is substituted. */
    text: trimmed.min(1).max(4000),
    /** Drives the CTA target and the callback form's preselected service. */
    serviceSlug: trimmed.max(80).nullable().default(null),
    /** Shown on the service page's FAQ block, as `show_on_page` did. */
    faqQuestion: trimmed.max(200).nullable().default(null),
  }),

  /** Asks the visitor something and stores the answer. */
  z.object({
    ...nodeBase,
    kind: z.literal("ask"),
    text: trimmed.min(1).max(1000),
    /** The `slot.key` this writes. */
    slot: trimmed.min(1).max(40),
  }),

  /** Routing only — no visitor-facing text. Its outgoing `slot` conditions are
   *  evaluated in edge order, and the first that holds wins. */
  z.object({ ...nodeBase, kind: z.literal("branch") }),

  /** Hands the turn to the model, grounded by `../retrieve.ts`. The only node
   *  kind that costs money, which is why it is explicit on the canvas. */
  z.object({
    ...nodeBase,
    kind: z.literal("model"),
    /** Prepended to the retrieved context. Lets an author narrow the model to
     *  the topic this branch is about. Empty means the system prompt alone. */
    guidance: trimmed.max(1000).default(""),
  }),

  /**
   * An answer read off the live jobs board.
   *
   * The one kind of question this site is asked most and the one an authored
   * answer cannot hold: a role is whatever the visitor does for a living, the
   * emirate is one of seven, and the listings turn over every week. Writing
   * those down would be a node per role per city, stale the day after the
   * ingest runs — and the flow has a node budget precisely because the whole
   * document is loaded per turn.
   *
   * So this box answers from `../jobs/board.ts` instead: matching listings with
   * their own links, or what those listings advertise as pay, or the posting
   * the visitor is currently reading. It costs a database query and no model
   * call, which makes it cheaper than the fallback it replaces as well as more
   * accurate — every figure in the reply is one an employer published.
   */
  z.object({
    ...nodeBase,
    kind: z.literal("jobs"),
    /**
     * `listings` shows what matches. `salary` says what those listings pay, and
     * only when enough of them state it. `posting` answers about the listing
     * the job page is showing, falling back to `listings` when the widget was
     * opened somewhere else.
     */
    answers: z.enum(["listings", "salary", "posting"]).default("listings"),
    /** Search terms for when the message names no role — what a tapped
     *  "Healthcare jobs" chip searches for. The visitor's own words win. */
    query: trimmed.max(120).default(""),
    /**
     * What to say when the data cannot answer: an empty board, or a role whose
     * listings do not state a salary.
     *
     * Authored rather than generated, because "there is nothing in Fujairah
     * this week, here is what to do instead" is advice, and advice published
     * under the company's name gets written by a person.
     */
    fallback: trimmed.min(1).max(2000),
    /** Drives the CTA target, exactly as on a `say`. */
    serviceSlug: trimmed.max(80).nullable().default(null),
  }),

  /** Opens the callback form. `reason` reaches the widget unchanged. */
  z.object({
    ...nodeBase,
    kind: z.literal("handoff"),
    text: trimmed.min(1).max(1000),
    /** Why a person is being brought in. "qualified" is the good one: the
     *  service has everything it needs and the callback form opens pre-filled. */
    reason: z
      .enum(["qualified", "budget", "unavailable", "contact", "requested"])
      .default("requested"),
    serviceSlug: trimmed.max(80).nullable().default(null),
  }),

  /**
   * Runs a service's qualification schema to completion.
   *
   * The reconciliation of "author the conversation" with "do not hard-code the
   * conversation": six required fields are six rows in the Service Builder and
   * *one* box here, not six boxes and six edges. The questions, their order and
   * what counts as answered all live in the service definition, so changing
   * them is an edit in the admin rather than a redraw.
   *
   * It asks one question per turn and stays put until nothing required is
   * missing, then takes its `always` edge.
   */
  z.object({
    ...nodeBase,
    kind: z.literal("qualify"),
    /** The slug of the service definition to run. */
    serviceId: trimmed.min(1).max(80),
  }),

  /** A deliberate end. Distinguishes "this conversation is finished" from "this
   *  node has no outgoing edge", which `lint.ts` otherwise reports as a fault. */
  z.object({ ...nodeBase, kind: z.literal("end") }),
]);

export const nodeKinds = [
  "start",
  "say",
  "ask",
  "qualify",
  "branch",
  "model",
  "jobs",
  "handoff",
  "end",
] as const;

/* ── Edges ───────────────────────────────────────────────────────────────── */

/**
 * Why an edge is taken.
 *
 * `intent` is the semantic one. `choice` is a tapped button, which is free and
 * exact. `slot` branches on something already collected. `always` is an
 * unconditional step, used after a `say` that leads somewhere. `fallback` is the
 * edge taken when nothing else matched — the thing today's bank has no way to
 * express, and the reason ambiguous questions currently go straight to the model
 * whether or not that is the best answer.
 */
export const edgeCondition = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("intent"), intentId: id }),
  z.object({ kind: z.literal("choice"), label: trimmed.min(1).max(60) }),
  z.object({
    kind: z.literal("slot"),
    slot: trimmed.min(1).max(40),
    op: z.enum(["eq", "neq", "exists", "missing"]),
    value: trimmed.max(120).default(""),
  }),
  z.object({ kind: z.literal("always") }),
  z.object({ kind: z.literal("fallback") }),
]);

export const flowEdge = z.object({
  id,
  from: id,
  to: id,
  when: edgeCondition,
  /**
   * Evaluation order among a node's outgoing edges, and the order buttons are
   * offered in. Explicit rather than array order because the canvas reorders
   * edges as a side effect of dragging, and a branch whose meaning changes when
   * you move a node is the worst kind of bug to find.
   */
  position: z.number().int().min(0).max(1_000_000).default(0),
  /**
   * Where the author dragged this arrow's labels to.
   *
   * Presentation, like a node's `position`, and stored for the same reason: a
   * label nudged out of a crowded corner has to still be there tomorrow, or
   * everyone does the nudging again every time they open the canvas.
   *
   * Two of them, because a long arrow has two ends and each is tagged. One
   * offset meant dragging the question at the receiving end also dragged the
   * "to 7" tag at the sending end, halfway across the diagram.
   */
  labelOffset: z.object({ x: z.number(), y: z.number() }).default({ x: 0, y: 0 }),
  /** The "to N" tag where the arrow leaves. */
  tagOffset: z.object({ x: z.number(), y: z.number() }).default({ x: 0, y: 0 }),
});

/* ── The document ────────────────────────────────────────────────────────── */

/**
 * Referential integrity is enforced here, not in `lint.ts`.
 *
 * The split: this schema is what *cannot be stored* — an edge pointing at a
 * node that does not exist is corruption, and no draft should hold it. `lint.ts`
 * is what *should not be published* — an unreachable node is a mistake, but it
 * is a mistake you want to be able to save halfway through fixing.
 */
/**
 * The ceilings, and what they cost.
 *
 * They bind on the whole document, which is loaded and cached on every turn and
 * whose every phrase is embedded at publish — so these are a budget, not a
 * formality, and they were raised once deliberately rather than drifting.
 *
 * Raised 2026-09-30 from 500/500/2000 to hold a fifth authored pack. Four packs
 * — attestation, notarisation, business setup and higher studies — are 672
 * entries, and an entry costs one node, one intent and roughly four edges (its
 * own edge from `start`, plus its chips and buttons).
 *
 * Raised again 2026-09-30, to 1500/1500/5600, for the translation and
 * interpretation pack. That is the "two hundred more answers" the previous note
 * budgeted for, so this is the decision it said would come due rather than a
 * drift.
 *
 * Sized against a measurement rather than the increment: the six packs that
 * build today — attestation, notarisation, business setup, higher studies,
 * visas and translation — are 1,119 entries, which is 1,133 nodes, 1,119
 * intents and 4,461 edges. A seventh, job search, is being written and is
 * roughly 124 entries, so the headroom above is about one more pack and not
 * two.
 *
 * The cost is real and paid on every turn: the whole document is loaded and
 * cached per conversation, and every phrase is embedded at publish. The next
 * raise should therefore be a decision about whether an eighth subject belongs
 * in one graph at all, rather than another number.
 *
 * Edges raised to 6500 on 2026-10-01, measured rather than budgeted: job search
 * landed at 250 entries, not the 124 estimated above, so the seven packs that
 * build today are 1,369 entries — 1,385 nodes, 1,369 intents and 5,537 edges.
 * That left 63 edges of headroom, about sixteen entries, which is thin enough
 * that an ordinary afternoon's editing would have failed the seed with a raw zod
 * error. Nodes and intents are untouched because they are not the binding
 * constraint; edges are, because chips and buttons multiply per entry.
 *
 * Raised again 2026-10-01 to 1750/1750/7000, for the relocation pack — the
 * eighth subject, and the decision the note above said would come due. It was
 * taken rather than avoided for one reason: the eight packs answer one person's
 * journey, not eight subjects. Somebody moving here for a job walks from a job
 * question into a visa question into a document question in three messages, and
 * a visitor cannot be asked which graph they are in. The cost is real and is
 * paid per turn — the whole document is loaded and cached per conversation, and
 * every phrase is embedded at publish.
 *
 * Measured, not budgeted: the eight packs are 1,572 entries, which is 1,588
 * nodes, 1,572 intents and 6,408 edges. The headroom above that is deliberately
 * about one more pack's worth of *editing* and not a ninth pack: roughly 160
 * nodes, of which the ~45 legacy answers from `scripts/migrate-answers-to-flow.ts`
 * take a third.
 *
 * A ninth subject should not be another raise. At that point the honest change
 * is to stop loading one document per turn — a per-subject subgraph loaded on
 * demand, which `./subgraph.ts` already has the shape of — because the cost here
 * is linear in the whole graph while a conversation only ever walks one corner
 * of it.
 */
export const flowDoc = z
  .object({
    nodes: z.array(flowNode).min(1).max(1750),
    edges: z.array(flowEdge).max(7000),
    intents: z.array(intent).max(1750),
    slots: z.array(slot).max(50),
  })
  .superRefine((doc, ctx) => {
    const nodeIds = new Set<string>();
    for (const node of doc.nodes) {
      if (nodeIds.has(node.id)) {
        ctx.addIssue({ code: "custom", message: `duplicate node id: ${node.id}`, path: ["nodes"] });
      }
      nodeIds.add(node.id);
    }

    const intentIds = new Set<string>();
    for (const i of doc.intents) {
      if (intentIds.has(i.id)) {
        ctx.addIssue({ code: "custom", message: `duplicate intent id: ${i.id}`, path: ["intents"] });
      }
      intentIds.add(i.id);
    }

    const slotKeys = new Set(doc.slots.map((s) => s.key));
    if (slotKeys.size !== doc.slots.length) {
      ctx.addIssue({ code: "custom", message: "duplicate slot key", path: ["slots"] });
    }

    const starts = doc.nodes.filter((n) => n.kind === "start");
    if (starts.length !== 1) {
      ctx.addIssue({
        code: "custom",
        message: `a flow needs exactly one start node, found ${starts.length}`,
        path: ["nodes"],
      });
    }

    for (const node of doc.nodes) {
      if (node.kind === "ask" && !slotKeys.has(node.slot)) {
        ctx.addIssue({
          code: "custom",
          message: `node ${node.id} writes unknown slot "${node.slot}"`,
          path: ["nodes"],
        });
      }
    }

    const edgeIds = new Set<string>();
    for (const edge of doc.edges) {
      if (edgeIds.has(edge.id)) {
        ctx.addIssue({ code: "custom", message: `duplicate edge id: ${edge.id}`, path: ["edges"] });
      }
      edgeIds.add(edge.id);

      if (!nodeIds.has(edge.from)) {
        ctx.addIssue({ code: "custom", message: `edge ${edge.id} leaves unknown node ${edge.from}`, path: ["edges"] });
      }
      if (!nodeIds.has(edge.to)) {
        ctx.addIssue({ code: "custom", message: `edge ${edge.id} points at unknown node ${edge.to}`, path: ["edges"] });
      }
      if (edge.when.kind === "intent" && !intentIds.has(edge.when.intentId)) {
        ctx.addIssue({ code: "custom", message: `edge ${edge.id} uses unknown intent ${edge.when.intentId}`, path: ["edges"] });
      }
      if (edge.when.kind === "slot" && !slotKeys.has(edge.when.slot)) {
        ctx.addIssue({ code: "custom", message: `edge ${edge.id} reads unknown slot "${edge.when.slot}"`, path: ["edges"] });
      }
    }
  });

export type Slot = z.infer<typeof slot>;
export type SlotKind = z.infer<typeof slotKind>;
export type Intent = z.infer<typeof intent>;
export type FlowNode = z.infer<typeof flowNode>;
export type NodeKind = FlowNode["kind"];
export type EdgeCondition = z.infer<typeof edgeCondition>;
export type FlowEdge = z.infer<typeof flowEdge>;
export type FlowDoc = z.infer<typeof flowDoc>;

/** A node kind that can carry a reply the visitor reads. */
export type SpeakingNode = Extract<FlowNode, { text: string }>;

/* ── Reading the graph ───────────────────────────────────────────────────── */

/**
 * An index built once per loaded flow, because the runtime asks the same three
 * questions on every turn and a linear scan of `edges` per question is the one
 * cost that grows with the size of the canvas.
 */
export interface FlowIndex {
  doc: FlowDoc;
  node: Map<string, FlowNode>;
  intent: Map<string, Intent>;
  slot: Map<string, Slot>;
  /** Outgoing edges per node, already in evaluation order. */
  out: Map<string, FlowEdge[]>;
  start: FlowNode;
}

export function indexFlow(doc: FlowDoc): FlowIndex {
  const out = new Map<string, FlowEdge[]>();
  for (const edge of doc.edges) {
    const list = out.get(edge.from);
    if (list) list.push(edge);
    else out.set(edge.from, [edge]);
  }
  for (const list of out.values()) list.sort((a, b) => a.position - b.position);

  const start = doc.nodes.find((n) => n.kind === "start");
  // `flowDoc` guarantees this; the throw is for a doc built in memory by a test
  // or a migration that skipped parsing.
  if (!start) throw new Error("flow has no start node");

  return {
    doc,
    node: new Map(doc.nodes.map((n) => [n.id, n])),
    intent: new Map(doc.intents.map((i) => [i.id, i])),
    slot: new Map(doc.slots.map((s) => [s.key, s])),
    out,
    start,
  };
}

/** Every phrase the flow would embed, deduplicated. The publish step turns this
 *  into vectors; `intents.ts` matches against them. */
export function embeddablePhrases(doc: FlowDoc): string[] {
  const seen = new Set<string>();
  for (const i of doc.intents) {
    // The intent's own name is embedded too. It is written as a topic rather
    // than a question, which is exactly the phrasing some visitors use.
    for (const phrase of [i.name, ...i.phrases]) {
      const key = phrase.trim().toLowerCase();
      if (key) seen.add(key);
    }
  }
  return [...seen];
}
